### ISSUE TITLE
Why were js.dart and others deprecated?

### ISSUE THREAD

**Issue by dannnnthemannnn** [dint-dev/web_browser#20]
Is there a better solution than using this package for those?

**Comment by terrier989** [comment]
Hi!

Thanks for the issue report! :) They libraries were originally added because 'dart:html' APIs had some references to _dart:svg_, etc. However, it became apparent that some Flutter developers are using _package:universal_html_ for purposes the package was not designed for. The aim of the deprecation was to save those developers' time by discouraging people from using _package:universal_html_ incorrectly.

Developers dealing with Javascript libraries should use [pub.dev/packages/js](https://pub.dev/packages/js), which is the official package by Google and is much easier to use than _dart:js_. Cross-platform Flutter code can be achieved with conditional imports/exports.
